<div id="preloader" style="display: none;" class="preloader-overlay">
    {{-- <div class="preloader-spinner"></div> --}}

    <svg width="48" height="56" viewBox="0 0 48 56" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M14 31V16H10.5" stroke="var(--color-main)" stroke-width="3" stroke-linecap="round" class="svg-elem-1-">
        </path>
        <path
            d="M36.7444 21.5589C36.3821 20.2067 35.6486 18.9829 34.6269 18.026C33.6052 17.0691 32.3361 16.4172 30.9632 16.1441C29.5902 15.871 28.1683 15.9876 26.8581 16.4807C25.548 16.9738 24.402 17.8237 23.5499 18.9343C22.6977 20.0449 22.1733 21.3718 22.0361 22.7649C21.8989 24.158 22.1543 25.5617 22.7735 26.8172C23.3926 28.0727 24.3507 29.1298 25.5395 29.869C26.7282 30.6082 28.1002 31 29.5 31H44.5"
            stroke="var(--color-main)" stroke-width="3" stroke-linecap="round" class="svg-elem-4-"></path>

        <path d="M6 54H42" stroke="var(--color-brand)" stroke-width="3" stroke-linecap="round" class="svg-elem-2">
        </path>
        <path
            d="M41.6887 37.9054C38.4716 41.9977 33.9351 44.848 28.8521 45.9706C23.7691 47.0932 18.4541 46.4185 13.8127 44.0616C9.17136 41.7048 5.4908 37.8115 3.39816 33.0451C1.30553 28.2788 0.930292 22.9343 2.3364 17.9223C3.7425 12.9103 6.84295 8.54093 11.1095 5.55864C15.376 2.57634 20.5445 1.16566 25.7345 1.56696C30.9246 1.96826 35.8148 4.1567 39.5722 7.75941C43.3295 11.3621 45.7215 16.1562 46.3404 21.3248"
            stroke="var(--color-brand)" stroke-width="3" stroke-linecap="round" class="svg-elem-3"></path>
        <path d="M24 54V47" stroke="var(--color-brand)" stroke-width="3" stroke-linecap="round" class="svg-elem-5">
        </path>
    </svg>

</div>

<style>
    .preloader-overlay {
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(255, 255, 255, 0.9);
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .preloader-spinner {
        width: 40px;
        height: 40px;
        border: 4px solid var(--color-other);
        border-top-color: var(--color-brand);
        border-radius: 50%;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }

    /***************************************************
    * Generated by SVG Artista on 8/12/2025, 4:36:35 PM
    * MIT license (https://opensource.org/licenses/MIT)
    * W. https://svgartista.net
    **************************************************/

    @-webkit-keyframes animate-svg-stroke-1 {
        0% {
            stroke-dashoffset: 20.5px;
            stroke-dasharray: 20.5px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 20.5px;
        }

        100% {
            stroke-dashoffset: 20.5px;
            stroke-dasharray: 20.5px;
        }
    }

    @keyframes animate-svg-stroke-1 {
        0% {
            stroke-dashoffset: 20.5px;
            stroke-dasharray: 20.5px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 20.5px;
        }

        100% {
            stroke-dashoffset: 20.5px;
            stroke-dasharray: 20.5px;
        }
    }

    .svg-elem-1 {
        -webkit-animation: animate-svg-stroke-1 1s ease 0s both infinite;
        animation: animate-svg-stroke-1 1s ease 0s both infinite;
    }

    @-webkit-keyframes animate-svg-stroke-2 {
        0% {
            stroke-dashoffset: 38px;
            stroke-dasharray: 38px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 38px;
        }

        100% {
            stroke-dashoffset: 38px;
            stroke-dasharray: 38px;
        }
    }

    @keyframes animate-svg-stroke-2 {
        0% {
            stroke-dashoffset: 38px;
            stroke-dasharray: 38px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 38px;
        }

        100% {
            stroke-dashoffset: 38px;
            stroke-dasharray: 38px;
        }
    }

    .svg-elem-2 {
        -webkit-animation: animate-svg-stroke-2 1s ease 0s both infinite;
        animation: animate-svg-stroke-2 1s ease 0s both infinite;
    }

    @-webkit-keyframes animate-svg-stroke-3 {
        0% {
            stroke-dashoffset: 125.70034790039062px;
            stroke-dasharray: 125.70034790039062px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 125.70034790039062px;
        }

        100% {
            stroke-dashoffset: 125.70034790039062px;
            stroke-dasharray: 125.70034790039062px;
        }
    }

    @keyframes animate-svg-stroke-3 {
        0% {
            stroke-dashoffset: 125.70034790039062px;
            stroke-dasharray: 125.70034790039062px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 125.70034790039062px;
        }

        100% {
            stroke-dashoffset: 125.70034790039062px;
            stroke-dasharray: 125.70034790039062px;
        }
    }

    .svg-elem-3 {
        -webkit-animation: animate-svg-stroke-3 1s ease 0s both infinite;
        animation: animate-svg-stroke-3 1s ease 0s both infinite;
    }

    @-webkit-keyframes animate-svg-stroke-4 {
        0% {
            stroke-dashoffset: 50.37946319580078px;
            stroke-dasharray: 50.37946319580078px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 50.37946319580078px;
        }

        100% {
            stroke-dashoffset: 50.37946319580078px;
            stroke-dasharray: 50.37946319580078px;
        }
    }

    @keyframes animate-svg-stroke-4 {
        0% {
            stroke-dashoffset: 50.37946319580078px;
            stroke-dasharray: 50.37946319580078px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 50.37946319580078px;
        }

        100% {
            stroke-dashoffset: 50.37946319580078px;
            stroke-dasharray: 50.37946319580078px;
        }
    }

    .svg-elem-4 {
        -webkit-animation: animate-svg-stroke-4 1s ease 0s both infinite;
        animation: animate-svg-stroke-4 1s ease 0s both infinite;
    }

    @-webkit-keyframes animate-svg-stroke-5 {
        0% {
            stroke-dashoffset: 9px;
            stroke-dasharray: 9px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 9px;
        }

        1000% {
            stroke-dashoffset: 9px;
            stroke-dasharray: 9px;
        }
    }

    @keyframes animate-svg-stroke-5 {
        0% {
            stroke-dashoffset: 9px;
            stroke-dasharray: 9px;
        }

        50% {
            stroke-dashoffset: 0;
            stroke-dasharray: 9px;
        }

        100% {
            stroke-dashoffset: 9px;
            stroke-dasharray: 9px;
        }
    }

    .svg-elem-5 {
        -webkit-animation: animate-svg-stroke-5 1s ease 0s both infinite;
        animation: animate-svg-stroke-5 1s ease 0s both infinite;
    }
</style>

<script>
    window.showPreloader = () => {
        document.getElementById('preloader').style.display = 'flex';
    };

    window.hidePreloader = () => {
        document.getElementById('preloader').style.display = 'none';
    };

    document.addEventListener("DOMContentLoaded", () => {
        showPreloader();
    });

    window.addEventListener("load", () => {
        hidePreloader();
    });

    window.addEventListener('pageshow', (event) => {
        if (event.persisted) {
            hidePreloader();
            console.log(1);
        }
    });
</script>
